### ISSUE TITLE
Performance Roadmap

### ISSUE THREAD

**Issue by kring** [CesiumGS/cesium-unreal#867]
This issue is an inventory of issues and ideas for improving Cesium for Unreal's performance. While we think the performance is pretty good, improved performance has a major impact on the user experience, so it's something worth investing in.

This is a work in progress, please add to it!

# Avoiding copies

Large objects like meshes and textures can take some time to copy, so we should do it as little as possible.

* [ ] https://github.com/CesiumGS/cesium-native/issues/375
* [ ] https://github.com/CesiumGS/cesium-unreal/issues/865

# Loading and rendering fewer tiles

Loading tiles takes time and network bandwidth. Preparing them for rendering burns CPU and GPU cycles as well as memory bandwidth. And actually rendering them does, too. So a tile not loaded and rendered is a big win.

* [ ] https://github.com/CesiumGS/cesium-unreal/issues/818
* [ ] https://github.com/CesiumGS/cesium-native/issues/342
* [ ] https://github.com/CesiumGS/cesium-native/issues/506
* [ ] https://github.com/CesiumGS/cesium-native/issues/483

# Prefetching

If we can predict which tiles are needed and load them ahead of time, we won't need to make the user wait while we load them later.

* [ ] https://github.com/CesiumGS/cesium-native/issues/85
* [ ] https://github.com/CesiumGS/cesium-native/issues/86
* [ ] https://github.com/CesiumGS/cesium-native/issues/266

# The Appearance of Performance

Sometimes we can do things that make the application _feel_ faster, even though it's not.

* [ ] https://github.com/CesiumGS/cesium-native/issues/269
* [ ] https://github.com/CesiumGS/cesium-unreal/issues/508

# Reducing GPU Load

Reducing the amount of work the GPU has to do, especially fragment processing work.

* [ ] https://github.com/CesiumGS/cesium-native/issues/88
* [ ] https://github.com/CesiumGS/cesium-unreal/issues/866

# Optimizing the load pipeline

Make the process of loading a tile faster. This can be a direct optimization, or it can mean skipping steps that aren't needed, perhaps driven by a user option.

* [ ] https://github.com/CesiumGS/cesium-unreal/issues/512

# Using Unreal Engine more efficiently

We may be doing some non-optimal things in our interaction with Unreal Engine that cost us performance.

* [ ] https://github.com/CesiumGS/cesium-unreal/issues/826
* [ ] https://github.com/CesiumGS/cesium-unreal/issues/490
* [ ] https://github.com/CesiumGS/cesium-unreal/issues/814

# Reducing memory usage

High memory usage is especially problematic on mobile devices.

* [ ] https://github.com/CesiumGS/cesium-native/issues/107
